### PR TITLE
Update weapons.json

### PR DESCRIPTION
**Pull request by enderrrrrrrrrr**
Adds m110 from RH AAR

### CODE REVIEW

**Comment by KoffeinFlummi** [comment]
Looks like Travis fucked up, but that probably isn't related to this...
(Also, @bux578, since when do we use this god awefull abonimation known as Ruby?)

Anyways, thanks for your contribution, although I think the M110 is from the M4/M16 pack, not the attachments pack. ;)

**Comment by bux578** [comment]
Ruby? Because of Sass. libsass isn't as far as ruby sass and not all of the plugins are ported yet.



—
JD

**Comment by bux578** [comment]
But changing to libsass is on my agenda. Firstly it takes only a fraction to compile and secondly it's not ruby.

**Comment by KoffeinFlummi** [comment]
> Firstly it takes only a fraction to compile and secondly it's not ruby.

I have a feeling that those two might be related... :confused:

**Pull request merged**
