### PR TITLE
Update weapons.json

### PR DESCRIPTION
**Pull request by enderrrrrrrrrr**

### CODE REVIEW

**Comment by KoffeinFlummi** [comment]
Thanks for your contribution!

**Comment by bux578** [comment]
The AR15 is an assault rifle, isn't it?

**Comment by bux578** [comment]
The LAR-15 is an assault rifle with 5.56 munition, isn't it?

**Comment by bux578** [comment]
We certainly don't need an entry for every tracer color.

**Comment by enderrrrrrrrrr** [comment]
Sorry for the late reply, the LAR-15 is a DMR. Perhaps not necessary, not
sure how specific you want to be with your rifles but i agree with the
tracer i just sort of grabbed everything that was extracted from the client
and put it in there. I will be more exacting in the future!

**Comment by bux578** [comment]
> the LAR-15 is a DMR

Didn't know that. The 5.56 munition made me wonder if anyone would even consider this as a DMR :)

**Comment by enderrrrrrrrrr** [comment]
I agree actually, feel more than welcome to remove it. I imagine it would
be a good line in the sand to keep it above 7.62 although the example i was
given when i inquired about this very issue was the C7CT and C8CT.

**Pull request merged**
