### PR TITLE
Update weapons.json

### PR DESCRIPTION
**Pull request by Cookie1993**
Added the L115A1 from Community Upgrade Project, CUP

### CODE REVIEW

**Comment by bux578** [comment]
Thanks :)
One change request though: I'd like to keep all RHS Weapons in one Mod.
`"mod": "RHS: United States Armed Forces",` should be `"mod": "RHS: Escalation",` (or similar)

**Comment by KoffeinFlummi** [comment]
Are you sure this is an RHS weapon? The classname seems to suggest that it's from CUP.

**Comment by Cookie1993** [comment]
Sry my bad :/

**Comment by KoffeinFlummi** [comment]
Added in #34.

**Pull request closed without merging**
